### PR TITLE
Added support for UART Bluetooth module

### PR DESCRIPTION
**Pull request by stephen99scott**
# Summary of Changes
* Set up LPUART1 for TX/RX to/from the Adafruit Bluefruit chip
* Confirmed functionality on the Nucleo because the lpuart pins C0/C1 are not available on the Discovery board
* Used the Bluefruit LE Connect app to confirm data received by my phone
Screenshot of data received
Nucleo connected to Adafruit Bluefruit

### CODE REVIEW

**Comment by adambujak** [comment]
looks very good! can you rebase to master to remove the docker stuff from this though? It will get confusing to merge this like this. Also I've been using 2 spaces instead of tabs for indents. I'll add a formatter soon.

**Comment by adambujak** [comment]
i think ble uart should be an application level module

**Comment by stephen99scott** [comment]
> i think ble uart should be an application level module

See latest commit

**Review by adambujak — APPROVED** [review]
looks good

**Pull request merged**
