### PR TITLE
Added Dockerfile for building firmware

### PR DESCRIPTION
**Pull request by stephen99scott**
As the title implies...
* Use `docker build . -t buildenv` in the firmware directory to create the docker image
* Use `docker run --rm -it -v ${pwd}:/root/env buildenv` in the firmware directory to start up a docker container
* In the docker container, navigate to `firmware/applications/SignBuddy` and use `make` to build the source code

### CODE REVIEW

**Review by harneetMac — COMMENTED** [review]
I'm getting the following error when I run 'make' command:
image

**Review by harneetMac — APPROVED** [review]
Just wanted to let you know that it was successful:
image

**Review by adambujak — CHANGES_REQUESTED** [review]
Can we please make this like the docker setup we made for neudose where i don't have to connect to the docker session to build

```
#! /bin/sh

# Create the docker container
docker create -it --name SDK sdk_image bash
# Start the docker container
docker start SDK
# Remove old source code from the docker container
docker exec -i SDK bash -c "cd /workspace/sdk && rm -rf src include lib"
# Copy new source code to the docker container
docker cp -a gs-sdk/src SDK:/workspace/sdk/
docker cp -a gs-sdk/include SDK:/workspace/sdk/
docker cp -a gs-sdk/lib SDK:/workspace/sdk/
docker cp -a gs-sdk/wscript SDK:/workspace/sdk/
docker cp -a gs-sdk/tools SDK:/workspace/sdk/
# Build the source code
docker exec SDK ./waf configure build
# Copy the build to the host
docker cp -a SDK:/workspace/sdk/build gs-sdk/
# Remove the docker container
docker rm -f SDK
```

**Comment by stephen99scott** [comment]
> Can we please make this like the docker setup we made for neudose where i don't have to connect to the docker session to build
* Please see the latest commit, added two scripts to build the source
* `new_dependencies.sh` is only needed if we have to add any more dependencies because it's slow to re-copy that folder to the docker container, otherwise, just use `compile.sh`

**Comment by adambujak** [comment]
I think this could be done better. See my branch ab/dockerfile. You don't have to copy the folders to the docker container, and I don't like how you have to run a different script when there are new dependency changes.

**Review by adambujak — APPROVED** [review]
lgtm

**Pull request merged**
