### PR TITLE
Modify workflow

### PR DESCRIPTION
**Pull request by stephen99scott**
Actions using the same docker image should be run under the same job so that the image doesn't have to be recreated for each job. There is one job for testing/building the firmware with multiple steps for each test, and I added in a job to build the Android app

### CODE REVIEW

**Comment by adambujak** [comment]
I disagree with this very much. These things are not related and perhaps should be run in a different docker image. 

Rebuilding these docker images between each task guarantees separation and no conflicts between the tasks. 

Putting them all under one task reduces the clarity of the different checks happening, because it'll just be one process running for a long time with a generic name. Also if the build fails, I'm pretty sure the rest of the checks will just not execute which is not what we want.

**Comment by adambujak** [comment]
I think it would be good to separate them into different docker images, so we don't have to install the whole arm-gcc just to run the formatter.

**Comment by adambujak** [comment]
we should probably just cache the docker builds https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

**Comment by stephen99scott** [comment]
> Rebuilding these docker images between each task guarantees separation and no conflicts between the tasks.

These are not running in the same docker image, they are using the same docker image to create their own containers, each container has no impact on the other containers as they do not modify the image.
> Putting them all under one task reduces the clarity of the different checks happening, because it'll just be one process running for a long time with a generic name. Also if the build fails, I'm pretty sure the rest of the checks will just not execute which is not what we want.

It is clear which tests are running by looking at the steps, github actions clearly distinguish between the different steps. And you can make steps run using an "if always" command, so that way all the tests are still run. I don't see any benefit in creating new docker images as that's what the purpose of containers is for

**Comment by adambujak** [comment]
> These are not running in the same docker image, they are using the same docker image to create their own containers, each container has no impact on the other containers as they do not modify the image.

You're right they don't. I was thinking that one could modify the code and cause issues down the line for the other checks, but you're right, each docker container is loaded with a fresh copy of the firmware each time. 

Even still separating the checks into different github actions is standard and is nice because you can easily see which checks failed or passed without going into the logs. 

I'll look into it more but I'm pretty sure this is the standard way to set this up and is cleaner than adding ifs to make it keep running even if a check failed.

**Comment by stephen99scott** [comment]
> I'll look into it more but I'm pretty sure this is the standard way to set this up and is cleaner than adding ifs to make it keep running even if a check failed.

To me it seems like if tests are using the same docker image they should be run in the same job, it's not a very good use of resources to create multiple docker images if they're all using the same base ubuntu image with only a couple package differences. imo since it is more efficient to run the tests in this manner and there is no difference in the results then we should do it this way

**Comment by stephen99scott** [comment]
If caching can reduce the image build time then that could also be another route if we want to have separate jobs for everything

**Comment by adambujak** [comment]
I find it very annoying to have to go into the logs to see what failed. But the faster speeds are nice. Let's figure out how to cache the docker images going forward

**Review by adambujak — APPROVED** [review]

**Comment by stephen99scott** [comment]
I can see how that's annoying for sure, I'll look into caching when I have some more time on my hands next week

**Pull request merged**
