### PR TITLE
Move cubemx file to hardware directory

### PR DESCRIPTION
**Pull request by stephen99scott**

### CODE REVIEW

**Comment by adambujak** [comment]
why did you delete the gitignore?

and why do we want to move this to hardware? this is a firmware generator project, no?

**Comment by adambujak** [comment]
why did you delete the gitignore?

and why do we want to move this to hardware? this is a firmware generator project, no?

**Comment by stephen99scott** [comment]
I was thinking we're not really using this file for project generation, we'll be referencing it as we design the pcb since the file shows all the pinouts

**Comment by adambujak** [comment]
@stephen99scott I think this should be in firmware, since it is firmware. Whether we use it for a reference in hardware is irrelevant imo. Anyway, i don't care where it is just please add the gitignore back

**Pull request closed without merging**
